// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WerkzeugShared;

#nullable disable

namespace WerkzeugShared.Migrations
{
    [DbContext(typeof(WerkzeugDbContext))]
    partial class WerkzeugDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("WerkzeugShared.DTO.ProjektDTO", b =>
                {
                    b.Property<string>("ProjektAddresse")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjektAddresse");

                    b.ToTable("Projekte");
                });

            modelBuilder.Entity("WerkzeugShared.DTO.ToolDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolTypeCountsSerialized")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ToolTypeCounts");

                    b.HasKey("Id");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("WerkzeugShared.DTO.UserDTO", b =>
                {
                    b.Property<string>("Benutzername")
                        .HasColumnType("TEXT");

                    b.Property<string>("Passwort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Benutzername");

                    b.ToTable("Benutzer");
                });

            modelBuilder.Entity("WerkzeugShared.DTO.WerkzeugDto", b =>
                {
                    b.Property<string>("WerkzeugId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Art")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("TEXT");

                    b.Property<string>("History")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Lager")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marke")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjektAdresse")
                        .HasColumnType("TEXT");

                    b.HasKey("WerkzeugId");

                    b.HasIndex("ProjektAdresse");

                    b.ToTable("Werkzeuge");
                });

            modelBuilder.Entity("WerkzeugShared.DTO.WerkzeugDto", b =>
                {
                    b.HasOne("WerkzeugShared.DTO.ProjektDTO", "Projekt")
                        .WithMany("Werkzeuge")
                        .HasForeignKey("ProjektAdresse");

                    b.Navigation("Projekt");
                });

            modelBuilder.Entity("WerkzeugShared.DTO.ProjektDTO", b =>
                {
                    b.Navigation("Werkzeuge");
                });
#pragma warning restore 612, 618
        }
    }
}
